### ISSUE TITLE
The command 'cobertura-merge' is not recognized

### ISSUE THREAD

**Issue by Roman1991** [cubonacci/cobertura-merge#11]
I recently installed the latest version of **cobertura-merge** package (0.4.0).
`npm install cobertura-merge`

`cobertura-merge -o output.xml package1=input1.xml package2=input2.xml`

When I try to run **cobertura-merge** command I receive the following message: 

> The term 'cobertura-merge' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

What am I doing wrong or is it just a bug?

**Comment by borremosch** [comment]
In order to run any binary installed by npm, you have to either:

1. Install it globally, i.e. `npm i -g cobertura-merge`, then run it using `cobertura-merge OPTIONS`
2. Install it locally, i.e. `npm i cobertura-merge`, then run it using `./node_modules/.bin/cobertura-merge OPTIONS`
3. Run it using npx, i.e. `npx cobertura-merge OPTIONS`

**Comment by Roman1991** [comment]
Thanks for a quick reply 👍 Please update the README file with the latest installation recommendations.
